name: Lint

on:
  push:
    branches:
      - main
    paths:
      - '**.ts'
      - '**.mts'
      - '**.cts'
      - '**.js'
      - '**.mjs'
      - '**.cjs'
      - '**.json'
      - '.github/workflows/lint.yml'
  pull_request:
    branches:
      - main
    paths:
      - '**.ts'
      - '**.mts'
      - '**.cts'
      - '**.js'
      - '**.mjs'
      - '**.cjs'
      - '**.json'
      - '.github/workflows/lint.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '14'
      - run: npm ci
      - run: npm run lint
